Dz2
yurwow/2024-2-VK-EDU-Frontend-Y-Kuzin pull request #2
Opened 2024-09-28 11:06 UTC by yurwow

# Домашнее задание №2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @uskov-anton проверить его.

Что было сделано:
1. Стилизовал форму отправки сообщений
2. Запрограммировал сохранение сообщений в localStorage и подгрузку из него при обновлении
3. Очистка input после нажатия Enter
4. Деплой странички на Github Pages: [https://yurwow.github.io/2024-2-VK-EDU-Frontend-Y-Kuzin/](https://yurwow.github.io/2024-2-VK-EDU-Frontend-Y-Kuzin/)
5. Также сделал кнопку прокрутки сообщений вниз и при отправке сообщения экран переходит вниз

2024-10-08 08:19 UTC, uskov-anton reviewed
Давай добавим где-нить кнопку, которая позволяет очищать сохраненные сообщения

2024-10-08 08:19 UTC, uskov-anton commented on simple-chat/src/index.html
> +        </style>
Давай стили вынесем в index.css

2024-10-08 08:19 UTC, uskov-anton commented on simple-chat/src/index.html
> +        </script>
Давай скрипты вынесем в index.js

2024-10-08 08:19 UTC, uskov-anton commented on simple-chat/src/index.html
> +                    <span>Nickname</span>
<img width="342" alt="Снимок экрана 2024-10-08 в 12 08 28" src="https://github.com/user-attachments/assets/336ae184-5856-45d4-99d5-4b8bf4255421">

Нужно поправить верстку:
- сделать в одну строку с обрезанием в виде троеточия
- добавить браузерный тултип (появляется при наведении), в котором отображать полное значение

2024-10-08 08:19 UTC, uskov-anton commented on simple-chat/src/index.css
> +body {
<img width="425" alt="Снимок экрана 2024-10-08 в 12 11 08" src="https://github.com/user-attachments/assets/4c44feb2-c485-4054-a06f-9b0e5a8bde2d">

При малых разрешениях экрана верстка кажется отображается не корректно. Тут либо надо делать адаптацию под разрешения, либо задавать минимальную ширину со скроллом горизонтальным.

2024-10-08 08:19 UTC, uskov-anton commented on simple-chat/src/index.html
> +                margin-left: 50px;
Отступы между элементами flex-контейнера лучше задавать через gap

2024-10-08 08:19 UTC, uskov-anton commented on simple-chat/src/index.html
> +                display: inline-block;
Кажется этот стиль ни на что не влияет

2024-10-08 08:19 UTC, uskov-anton commented on simple-chat/src/index.html
> +                <input class="form-input" name="message-text" placeholder="Написать сообщение" type="text">
Нужно добавить возможность вводить многострочный текст и также выводить его.

2024-10-08 08:19 UTC, uskov-anton commented on simple-chat/src/index.html
> +                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#e8eaed"><path d="M330-240q-104 0-177-73T80-490q0-104 73-177t177-73h370q75 0 127.
Кажется нужна не только иконка, но и функциональность прикрепления и вывода изображений (с сохранением в storage)

2024-10-12 13:39 UTC, martinkomitsky requested changes
Нужно исправить комментарии ментора

2024-10-15 18:25 UTC, uskov-anton commented on simple-chat/src/index.html
> +                    <span>Nickname</span>
<img width="651" alt="Снимок экрана 2024-10-15 в 22 24 51" src="https://github.com/user-attachments/assets/2518d347-a88d-4265-a0ce-a4f4c755be10">

При больших разрешениях обрезание выглядит странно, т.к. есть пустое пространство справа. Давай растягивать, если есть возможность, и обрезать, когда дальше тянуть некуда.

2024-10-18 16:25 UTC, uskov-anton commented on simple-chat/src/index.html
> +                    <span>Nickname</span>
<img width="653" alt="Снимок экрана 2024-10-18 в 20 24 53" src="https://github.com/user-attachments/assets/9dedf5a3-ee50-40bb-8bc6-704350b06313">

Лучше, но по-прежнему не достаточно. Попробуй без использования max-width достичь того же результата.

2024-10-21 15:56 UTC, uskov-anton commented on simple-chat/src/index.html
> +                margin-left: 50px;
Комментарий актуален для profile-container

2024-10-29 06:16 UTC, uskov-anton approved these changes

2024-11-10 11:09 UTC, martinkomitsky approved these changes

2024-11-10 11:10 UTC, martinkomitsky commented
12!

2024-11-10 11:10 UTC, merged