Dz3
yurwow/2024-2-VK-EDU-Frontend-Y-Kuzin pull request #3
Opened 2024-10-07 05:56 UTC by yurwow

# Домашнее задание №3

Прошу @martinkomitsky, @HaseProgram, @kgrechin или @uskov-anton проверить его.

Что было сделано:

1. Добавил sidebar меню
2. Теперь из чата можно выйти по кнопке и вернуться в него по клику из списка чатов в sidebar
3. Декомпозировал макет
4. Деплой: [https://yurwow.github.io/2024-2-VK-EDU-Frontend-Y-Kuzin/](https://yurwow.github.io/2024-2-VK-EDU-Frontend-Y-Kuzin/)

2024-10-23 16:57 UTC, martinkomitsky requested changes
Нужно исправить конфликт

2024-10-23 16:57 UTC, martinkomitsky commented
@uskov-anton будут комменты?

2024-11-10 11:11 UTC, martinkomitsky commented
@yurwow привет! смержил ДЗ2, тут появились конфликты.
Надо исправить тут, а потом в ДЗ 4 примержить ветку ДЗ 3, чтобы и там порешать их.

@uskov-anton ждем комменты

2024-11-11 17:31 UTC, uskov-anton commented on simple-chat/src/index.html
> +                        <div class="last-message span-online"></div>
Давай для ситуации, когда загружена картинка здесь будет выводить название файла

2024-11-11 17:31 UTC, uskov-anton commented on simple-chat/src/index.html
> +                <div class="chat-list">
Давай добавим еще 1-2 чата, чтобы можно было посмотреть как сохраняются сообщения по разным чатам

2024-11-11 17:33 UTC, uskov-anton commented on simple-chat/src/app.js
> +const chats = document.querySelector('.chat-container');
<img width="932" alt="Снимок экрана 2024-11-11 в 21 33 16" src="https://github.com/user-attachments/assets/9a82fa85-ecf8-4aec-ac5b-2916a3df8904">

не хватает декомпозиции приложения на отдельные компоненты

2024-11-11 17:34 UTC, uskov-anton commented
> @yurwow привет! смержил ДЗ2, тут появились конфликты. Надо исправить тут, а потом в ДЗ 4 примержить ветку ДЗ 3, чтобы и там порешать их.
> 
> @uskov-anton ждем комменты

Готово

2024-11-15 09:48 UTC, martinkomitsky commented
@yurwow конфликт

2024-11-19 14:52 UTC, martinkomitsky commented
@yurwow всё еще ждём конфликты и фиксы

2024-11-26 17:01 UTC, uskov-anton commented on simple-chat/src/app.js
> +const chats = document.querySelector('.chat-container');
@yurwow Этот комментарий еще актуален

2024-12-02 11:42 UTC, uskov-anton approved these changes

2024-12-09 10:45 UTC, martinkomitsky approved these changes

2024-12-09 10:45 UTC, merged